#!/usr/bin/env python3

import argparse
import pathlib
import runpy


VALUE_TYPES = {
    "bool", "float", "double", "int", "u32", "size_t",
    "ThemeVariant", "DockPosition", "DockClickAction", "BatteryDisplay",
    "FocusPolicy", "DecorationPolicy", "LayoutPolicy",
    "PointerAccelProfile", "TouchpadClickMethod", "TouchpadScrollMethod",
    "ToastPosition", "ScreenshotFormat", "ScreenshotAction",
    "BackendPreference", "SeatBackend", "TearingPolicy", "GestureAction",
    "NotificationPolicy", "ShortcutAction", "OutputRange",
}
REF_TYPES = {"ThemeColor", "ShortcutBinding", "NotificationRule",
             "InputDeviceSettings"}
WIDGETS = {"checkbox", "slider", "combo", "text", "multiline", "color",
           "time", "custom"}


def cap(name):
    return name[0].upper() + name[1:]


def cpp_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def validate(settings, pages):
    names = set()
    keys = set()
    groups = {page["name"] for page in pages}
    declared_names = {item["name"] for item in settings}

    for item in settings:
        name = item["name"]
        key = item["key"]
        mode = item["mode"]
        widget = item["widget"]

        if name in names:
            raise ValueError(f"duplicate setting name: {name}")
        if key in keys:
            raise ValueError(f"duplicate setting key: {key}")
        if item["group"] not in groups:
            raise ValueError(f"{name}: unknown group {item['group']}")
        if widget["kind"] not in WIDGETS:
            raise ValueError(f"{name}: unknown widget {widget['kind']}")
        if mode == "value" and item["type"] not in VALUE_TYPES:
            raise ValueError(f"{name}: unknown value type {item['type']}")
        if mode == "ref" and item["type"] not in REF_TYPES:
            raise ValueError(f"{name}: unknown reference type {item['type']}")
        if mode == "text" and item["type"] != "text":
            raise ValueError(f"{name}: text mode must use text type")
        if mode not in {"value", "ref", "text"}:
            raise ValueError(f"{name}: unknown mode {mode}")

        count = item.get("count")
        if count is not None:
            count_name = item.get("count_name")
            if not count_name:
                raise ValueError(f"{name}: indexed setting needs count_name")
            if count_name in declared_names:
                raise ValueError(f"{name}: count name conflicts with a setting")
            defaults = item["default"]
            if isinstance(defaults, list) and len(defaults) != count:
                raise ValueError(f"{name}: expected {count} defaults")

        names.add(name)
        keys.add(key)

    for page in pages:
        group = [
            item for item in settings if item["group"] == page["name"]
        ]
        custom_handlers = {
            item["widget"]["handler"] for item in group
            if item["widget"]["kind"] == "custom"
        }
        standard_widgets = [
            item["name"] for item in group
            if item["widget"]["kind"] != "custom"
        ]

        if len(custom_handlers) > 1:
            raise ValueError(
                f"{page['name']}: multiple custom page handlers")
        if custom_handlers and standard_widgets:
            raise ValueError(
                f"{page['name']}: custom and generated widgets are mixed")


def api_type(item):
    if item["mode"] == "text":
        return "stl::StringView"
    if item["mode"] == "ref":
        return f"const {item['type']}&"
    return item["type"]


def param_type(item):
    if item["mode"] == "text":
        return "stl::StringView"
    if item["mode"] == "ref":
        return f"const {item['type']}&"
    return item["type"]


def generate_header(settings):
    out = ["// generated by dev/gen_settings.py; do not edit", ""]

    for item in settings:
        name = item["name"]
        suffix = cap(name)
        index = "size_t index" if "count" in item else ""
        setter_index = "size_t index, " if "count" in item else ""

        if "count" in item:
            out.append(
                f"static constexpr size_t {item['count_name']} = {item['count']};")
        out.append(f"virtual {api_type(item)} {name}({index}) const = 0;")
        out.append(
            f"virtual void set{suffix}({setter_index}{param_type(item)} value) = 0;")
        out.append(
            f"virtual void add{suffix}Listener({setter_index}Listener* listener) = 0;")
        out.append("")

    return "\n".join(out)


def storage_default(item):
    if item["mode"] == "text":
        return "nullptr"
    if "count" in item:
        defaults = item["default"]
        if isinstance(defaults, list):
            return "{" + ", ".join(defaults) + "}"
        return "{}"
    return item["default"]


def generate_impl(settings):
    text_items = [item for item in settings if item["mode"] == "text"]
    out = [
        "// generated by dev/gen_settings.py; do not edit",
        '#include "settings.h"',
        "",
        '#include "composer.h"',
        '#include "keyboard.h"',
        '#include "listener.h"',
        '#include "intr_list.h"',
        "",
        "#include <std/dbg/assert.h>",
        "#include <std/lib/buffer.h>",
        "#include <std/mem/obj_pool.h>",
        "",
        "#include <xkbcommon/xkbcommon.h>",
        "",
        "using namespace stl;",
        "",
        "namespace {",
        "    void publish(IntrusiveList& listeners) {",
        "        forEach<Listener>(listeners, [](Listener& listener) {",
        "            listener.onListen();",
        "        });",
        "    }",
        "",
        "    struct SettingsComponent final: Settings {",
    ]

    for item in settings:
        name = item["name"]
        count = item.get("count")
        if item["mode"] == "text":
            value_type = "Buffer*"
        else:
            value_type = item["type"]
        suffix = f"[{count}]" if count is not None else ""
        out.append(f"        {value_type} {name}Value{suffix} = {storage_default(item)};")
        out.append(f"        IntrusiveList {name}Listeners{suffix};")
    initialized_text = [
        item for item in text_items if item["default"]
    ]
    if initialized_text:
        out += ["", "        SettingsComponent() {"]
        for item in initialized_text:
            out.append(
                f"            {item['name']}Value = "
                f"new Buffer(StringView({cpp_string(item['default'])}));")
        out += ["        }"]

    out += ["", "        ~SettingsComponent() noexcept override {"]
    for item in text_items:
        out.append(f"            delete {item['name']}Value;")
    out += ["        }", ""]

    for item in settings:
        name = item["name"]
        suffix = cap(name)
        count = item.get("count")
        idx_decl = "size_t index" if count is not None else ""
        idx = "[index]" if count is not None else ""
        assert_line = (
            f"            STD_ASSERT(index < {count});\n"
            if count is not None else "")
        setter_idx = "size_t index, " if count is not None else ""
        value_expr = f"{name}Value{idx}"
        listeners_expr = f"{name}Listeners{idx}"

        out.append(f"        {api_type(item)} {name}({idx_decl}) const override {{")
        if assert_line:
            out.append(assert_line.rstrip())
        if item["mode"] == "text":
            out.append(
                f"            return {value_expr} ? StringView(*{value_expr}) : StringView();")
        else:
            out.append(f"            return {value_expr};")
        out += ["        }", ""]

        out.append(
            f"        void set{suffix}({setter_idx}{param_type(item)} value) override {{")
        if assert_line:
            out.append(assert_line.rstrip())
        if item.get("normalize"):
            low, high = item["normalize"]
            out.append(
                f"            value = value < {low} ? {low} : value > {high} ? {high} : value;")
        if item["mode"] == "text":
            out += [
                f"            if ({name}({idx_decl and 'index'}) == value) {{",
                "                return;",
                "            }",
                "",
                "            Buffer* next = value.empty() ? nullptr : new Buffer(value);",
                f"            delete {value_expr};",
                f"            {value_expr} = next;",
            ]
        else:
            out += [
                f"            if ({value_expr} == value) {{",
                "                return;",
                "            }",
                "",
                f"            {value_expr} = value;",
            ]
        out += [
            f"            publish({listeners_expr});",
            "        }",
            "",
            f"        void add{suffix}Listener({setter_idx}Listener* listener) override {{",
        ]
        if assert_line:
            out.append(assert_line.rstrip())
        out += [
            f"            {listeners_expr}.pushBack(listener);",
            "        }",
            "",
        ]

    out += [
        "    };",
        "}",
        "",
        "Settings* Settings::create(Composer& composer) {",
        "    return composer.pool->make<SettingsComponent>();",
        "}",
        "",
    ]
    return "\n".join(out)


def emit_widget(item):
    name = item["name"]
    suffix = cap(name)
    label = cpp_string(item["label"])
    widget = item["widget"]
    kind = widget["kind"]
    widget_id = cpp_string(widget.get("id", ""))
    lines = [f"                row({label});"]

    if kind == "checkbox":
        lines += [
            f"                settingCheckbox({widget_id}, s, s.{name}(), &Settings::set{suffix});"
        ]
    elif kind == "slider":
        helper = "settingSliderInt" if item["type"] == "int" else "settingSliderFloat"
        lines += [
            f"                {helper}({widget_id}, s, s.{name}(), {widget['low']}, {widget['high']}, {cpp_string(widget['format'])}, &Settings::set{suffix});"
        ]
    elif kind == "combo":
        items = ", ".join(cpp_string(value) for value in widget["items"])
        lines += [
            "                {",
            f"                    constexpr const char* items[] = {{{items}}};",
            f"                    int value = (int)s.{name}();",
            f"                    if (ImGui::Combo({widget_id}, &value, items, (int)(sizeof(items) / sizeof(*items)))) {{",
            f"                        s.set{suffix}(({item['type']})value);",
            "                    }",
            "                }",
        ]
    elif kind == "text":
        lines += [
            f"                settingText({widget_id}, s, s.{name}(), &Settings::set{suffix});"
        ]
    elif kind == "color":
        lines += [
            "                {",
            f"                    ThemeColor value = s.{name}();",
            f"                    if (ImGui::ColorEdit3({widget_id}, &value.r, ImGuiColorEditFlags_DisplayRGB)) {{",
            f"                        s.set{suffix}(value);",
            "                    }",
            "                }",
        ]
    elif kind == "time":
        lines += [
            f"                settingTime({widget_id}, s, s.{name}(), &Settings::set{suffix});"
        ]
    else:
        raise ValueError(f"cannot emit {kind} widget for {name}")

    condition = widget.get("visible_if")
    if condition:
        lines = [f"                if ({condition}) {{"] + [
            "    " + line for line in lines
        ] + ["                }"]
    return lines


def generate_dialog(settings, pages):
    by_group = {page["name"]: [] for page in pages}
    for item in settings:
        by_group[item["group"]].append(item)

    out = [
        "// generated by dev/gen_settings.py; do not edit",
    ]

    shortcuts = next(
        (item for item in settings if item["name"] == "shortcut"), None)
    if shortcuts:
        defaults = shortcuts["default"]
        out += [
            "ShortcutBinding generatedShortcutDefault(size_t index) {",
            "    constexpr ShortcutBinding values[] = {",
        ]
        for value in defaults:
            out.append(f"        {value},")
        out += [
            "    };",
            "",
            "    STD_ASSERT(index < Settings::shortcutCount);",
            "    return values[index];",
            "}",
            "",
        ]

    out += [
        "constexpr const char* generatedSettingsPages[] = {",
    ]
    for page in pages:
        out.append(f"    {cpp_string(page['name'])},")
    out += [
        "};",
        "",
        "void Dialog::drawGeneratedPage(Composer& c, Settings& s) {",
        "    switch (page) {",
    ]

    for index, page in enumerate(pages):
        out.append(f"        case {index}:")
        custom_handlers = {
            item["widget"]["handler"] for item in by_group[page["name"]]
            if item["widget"]["kind"] == "custom"
        }
        if custom_handlers:
            handler = next(iter(custom_handlers))
            out.append(f"            {handler}(c, s);")
            out.append("            break;")
            continue

        out += [
            "            if (!beginRows()) {",
            "                break;",
            "            }",
        ]
        if page.get("prefix"):
            out.append(f"            {page['prefix']}(c);")

        after = []
        for item in by_group[page["name"]]:
            kind = item["widget"]["kind"]
            if kind == "custom":
                continue
            if kind == "multiline":
                after.append(item)
                continue
            out.extend(emit_widget(item))

        out.append("            ImGui::EndTable();")
        for item in after:
            suffix = cap(item["name"])
            widget = item["widget"]
            out += [
                f"            ImGui::SeparatorText({cpp_string(item['label'])});",
                f"            settingTextMultiline({cpp_string(widget['id'])}, s, s.{item['name']}(), ImGui::GetTextLineHeightWithSpacing() * {widget['lines']}.f, &Settings::set{suffix});",
            ]
        out.append("            break;")

    out += [
        "    }",
        "}",
        "",
    ]
    return "\n".join(out)


def write(path, content):
    target = pathlib.Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", required=True)
    parser.add_argument("--header", required=True)
    parser.add_argument("--impl", required=True)
    parser.add_argument("--dialog", required=True)
    args = parser.parse_args()

    schema = runpy.run_path(args.schema)
    settings = schema["SETTINGS"]
    pages = schema["PAGES"]
    validate(settings, pages)
    write(args.header, generate_header(settings))
    write(args.impl, generate_impl(settings))
    write(args.dialog, generate_dialog(settings, pages))


if __name__ == "__main__":
    main()
